connection:
    data:
        myConnection1:
            url: jdbc:mysql://localhost:3306/user_db
            username: root
            password: root
            driverClassName: com.mysql.cj.jdbc.Driver 
        myConnection2:
            url: jdbc:mysql://localhost:3306/orchestra
            username: root
            password: root
            driverClassName: com.mysql.cj.jdbc.Driver
spring:
    jpa:
      open-in-view: false
